name: bom_hamburguer
description: Bom Hamburguer shopping app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^4.2.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^1.5.4
  intl: ^0.17.0
  json_annotation: ^4.7.0

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.0
  injectable_generator: ^1.5.5
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
